FROM spdz/spdz:v0.3.4-workshop-voting

# Generate pre processing material to be used by SPDZ parties.
# Build container with:
#   docker build -f Dockerfile-spdz-preprocess -t spdz/spdz-preprocess .
# Run container with:
#   docker run -t --rm -u `id -u $USER`
#       -v /location/tostore/preprocess/data:/usr/spdz/Player-Data spdz/spdz-preprocess <number of parties, default is 2>

LABEL name="SPDZ MPC setup phase" \
      description="Run fake-offline pre-processing phase for specified number of SPDZ parties." \
      maintainer="Jonathan Evans <jon.evans@bristol.ac.uk>" \
      license="University of Bristol : Open Access Software Licence" 

VOLUME /usr/spdz/Player-Data

ENTRYPOINT ["Scripts/setup-online.sh"]

CMD ["2"]
