FROM spdz/spdz:privateclient_2b1cb7

# Compile the workshop_voting mpc program into the container and setup hooks to pass in run time information.
# Build container with:
#   docker build -f Dockerfile-workshop-voting -t spdz/workshop-voting .
# Run container with - see Scripts/run-spdz.sh

LABEL name="SPDZ MPC Party Runtime" \
      description="Compile a SPDZ MPC program and provide run time hooks." \
      maintainer="Jonathan Evans <jon.evans@bristol.ac.uk>" \
      license="University of Bristol : Open Access Software Licence" 

#TODO copy in workshop_voting program at build time
#Optional compiler args e.g. -M

RUN ./compile.py workshop_voting

ENV playerId=0

ENV startupHost=localhost

# server ports to listen on depend on player id (14010 + playerId, 14020 + playerId, 13000 + playerId)
# expose at run time with --expose and -p.

# Pass in offline data at run time for specific player 
VOLUME /home/spdzuser/spdz/Player-Data

# Store logs onto host file system
VOLUME /home/spdzuser/spdz/logs

ENTRYPOINT exec ./Player-Online.x -lgp 128 -lg2 40 -m empty -h $startupHost -pn 13000 $playerId workshop_voting \
 > /home/spdzuser/spdz/logs/$playerId 2>&1
