FROM spdz/spdz:v0.3.0-workshop-voting

# Compile the workshop_voting mpc program into the container and setup hooks to pass in run time information.
# Build container with:
#   docker build -f Dockerfile-workshop-voting -t spdz/workshop-voting .
# Run container with - see Scripts/run-spdz.sh

LABEL name="SPDZ MPC Party Runtime" \
      description="Compile a SPDZ MPC program and provide run time hooks." \
      maintainer="Jonathan Evans <jon.evans@bristol.ac.uk>" \
      license="University of Bristol : Open Access Software Licence" 

# Optional compiler args e.g. -M
ARG compilerArgs=''

COPY buildtemp/workshop_voting.mpc Programs/Source

RUN ./compile.py $compilerArgs workshop_voting

ENV playerId=0
ENV startupHost=localhost
ENV basePort=13000

# server ports to listen on depend on player id (14010 + playerId, 14020 + playerId, 13000 + playerId)
# expose at run time with --expose and -p.

# Pass in offline data at run time for specific player 
VOLUME /usr/spdz/Player-Data

# Store logs onto host file system
VOLUME /usr/spdz/logs

ENTRYPOINT exec ./Player-Online.x -lgp 128 -lg2 40 -m empty -h $startupHost -pn $basePort $playerId workshop_voting \
 > /usr/spdz/logs/$playerId 2>&1
