FROM centos:7

# Build container with:
#   docker build -f Dockerfile-gcc -t spdz/gcc:6.2 .
# Give docker as many cores as possible, this takes ~ 1 hour.

LABEL name="Centos with later GCC" \
      description="Install a later GCC toolchain than provided with Centos." \
      maintainer="Jonathan Evans <jon.evans@bristol.ac.uk>" \
      license="University of Bristol : Open Access Software Licence" 

RUN yum update -y 

# Centos 7 supported gcc 4.8.5
RUN yum -y groupinstall "Development Tools"
RUN yum -y install wget
RUN yum -y install zlib-devel
RUN yum -y install which

# Following copied from gcc docker file
ENV GPG_KEYS \
	B215C1633BCA0477615F1B35A5B3A004745C015A \
	B3C42148A44E6983B3E4CC0793FA9B1AB75C61B8 \
	90AA470469D3965A87A5DCB494D03953902C9419 \
	80F98B2E0DAB6C8281BDF541A7C8C3B2F71EDF1C \
	7F74F97C103468EE5D750B583AB00996FC26A641 \
	33C235A34C46AA3FFB293709A328C3A2C3C45C06

RUN set -xe \
	&& for key in $GPG_KEYS; do \
		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
	done

ENV GCC_VERSION 6.2.0

# This takes 1 hour plus on 2 cores.
RUN curl -fSL "http://ftpmirror.gnu.org/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.bz2" -o gcc.tar.bz2 \
	&& curl -fSL "http://ftpmirror.gnu.org/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.bz2.sig" -o gcc.tar.bz2.sig 
  && gpg --batch --verify gcc.tar.bz2.sig gcc.tar.bz2 \
	&& mkdir -p /usr/src/gcc \
	&& tar -xf gcc.tar.bz2 -C /usr/src/gcc --strip-components=1 \
	&& rm gcc.tar.bz2* \
	&& cd /usr/src/gcc \
	&& ./contrib/download_prerequisites \
	&& { rm *.tar.* || true; } \
	&& dir="$(mktemp -d)" \
	&& cd "$dir" \
	&& /usr/src/gcc/configure \
		--with-system-zlib \
    --disable-multilib \
		--enable-languages=c,c++ \
	&& make -j"$(nproc)" \
	&& make install-strip \
	&& cd .. \
	&& rm -rf "$dir"

# gcc installs .so files in /usr/local/lib64, add to library path.
RUN echo '/usr/local/lib64' > /etc/ld.so.conf.d/local-lib64.conf \
	&& ldconfig -v
