FROM spdz/libs:1.1

  # Assumes you have spdz checked out to host file system 
  # Build container with:
  #   docker build -f Dockerfile-spdz-dev -t spdz/spdzdev .
  # Run container with:
  #   docker run -it --rm -p 14000-14010:14000-14010 -v /Users/je0018/Development/spdz:/spdz spdz/spdzdev
  #   once running, can be used to run n parties, generate offline data etc.

LABEL name="SPDZ MPC Dev" \
      description="SPDZ MPC software dev environment, using host file system." \
      maintainer="Jonathan Evans <jon.evans@bristol.ac.uk>" \
      license="University of Bristol : Open Access Software Licence" 

# Setup dir and install python gmpy and networkx to allow tests to be run later.
RUN mkdir /spdz \
 && yum install -y epel-release \
 && yum install -y python-devel \
 && yum install -y python-pip \
 && yum install -y python-wheel \
 && pip install --upgrade pip \
 && pip install gmpy \
 && pip install networkx \
 && echo 'export PYTHONPATH=.' >> ~/.bash_profile \
 && source ~/.bash_profile 

VOLUME /spdz

EXPOSE 14000-14010

WORKDIR /spdz

CMD ["/bin/bash", "--login"]


