# Dev compose file to run voting app containers on a single host.
# Uses the default network to allow containers to connect via name.
# Start with docker-compose -f voting-dev.yml up
# Stop with docker-compose -f voting-dev.yml down
version: "3"
services:
  spdz-startup:
    image: spdz/spdz-startup:latest
    ports:
      - "12999:12999"
  workshop-voting0:
    image: spdz/workshop-voting:v0.3.4_dev
    depends_on:
      - spdz-startup
    expose:
      - "13000"
      - "14000"
    ports:
      - "13000:13000"
      - "14000:14000"
    environment:
      playerId: 0
      startupHost: spdz-startup
    volumes:
      - /Users/je0018/temp/Player-Data:/usr/spdz/Player-Data
      - /Users/je0018/temp/logs:/usr/spdz/logs
      - /Users/je0018/temp/Persistence:/usr/spdz/Persistence    
  workshop-voting1:
    image: spdz/workshop-voting:v0.3.4_dev
    depends_on:
      - spdz-startup
    expose:
      - "13001"
      - "14001"
    ports:
      - "13001:13001"
      - "14001:14001"
    environment:
      playerId: 1
      startupHost: spdz-startup
    volumes:
      - /Users/je0018/temp/Player-Data:/usr/spdz/Player-Data
      - /Users/je0018/temp/logs:/usr/spdz/logs
      - /Users/je0018/temp/Persistence:/usr/spdz/Persistence
  spdz-proxy0:
    image: spdz/spdz-proxy:v0.3.2_rc
    depends_on:
      - workshop-voting0
    ports:
      - "3010:8080"
    environment:
      SPDZ_HOST: workshop-voting0
      SPDZ_PORT: 14000
      REST_PORT: 8080
      LOG_LEVEL: debug
    volumes:
      - /Users/je0018/temp/spdzproxy:/usr/app/certs
      - /Users/je0018/temp/logs:/usr/app/logs
  spdz-proxy1:
    image: spdz/spdz-proxy:v0.3.2_rc
    depends_on:
      - workshop-voting1
    ports:
      - "3011:8080"
    environment:
      SPDZ_HOST: workshop-voting1
      SPDZ_PORT: 14001
      REST_PORT: 8080
      LOG_LEVEL: debug
    volumes:
      - /Users/je0018/temp/spdzproxy:/usr/app/certs
      - /Users/je0018/temp/logs:/usr/app/logs
  workshop-voting-gui:
    image: spdz/workshop-voting-gui:v0.1.3
    depends_on:
      - spdz-proxy0
      - spdz-proxy1
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      LOG_LEVEL: debug
    volumes:
      - /Users/je0018/temp/votinggui:/usr/app/certs
      - /Users/je0018/temp/votinggui:/usr/app/config
      - /Users/je0018/temp/logs:/usr/app/logs
