# Dev compose file to run voting app containers on a single host.
# Uses the default network to allow containers to connect via name.
# Start with docker-compose -f voting-dev.yml up
# Stop with docker-compose -f voting-dev.yml down
version: "3"
services:
  spdz-startup:
    image: spdz/spdz-startup:latest
    ports:
      - "12999:12999"
  workshop-voting0:
    image: spdz/workshop-voting:v0.3.5_dev
    depends_on:
      - spdz-startup
    expose:
      - "13000"
      - "14000"
    ports:
      - "13000:13000"
      - "14000:14000"
    environment:
      playerId: 0
      startupHost: spdz-startup
    volumes:
      - ${HOME}/temp/Player-Data:/usr/spdz/Player-Data
      - ${HOME}/temp/logs:/usr/spdz/logs
      - ${HOME}/temp/Persistence:/usr/spdz/Persistence    
  workshop-voting1:
    image: spdz/workshop-voting:v0.3.5_dev
    depends_on:
      - spdz-startup
    expose:
      - "13001"
      - "14001"
    ports:
      - "13001:13001"
      - "14001:14001"
    environment:
      playerId: 1
      startupHost: spdz-startup
    volumes:
      - ${HOME}/temp/Player-Data:/usr/spdz/Player-Data
      - ${HOME}/temp/logs:/usr/spdz/logs
      - ${HOME}/temp/Persistence:/usr/spdz/Persistence
  spdz-proxy0:
    image: spdz/spdz-proxy:v0.4.0
    depends_on:
      - workshop-voting0
    ports:
      - "3010:8080"
    environment:
      SPDZ_HOST: workshop-voting0
      SPDZ_PORT: 14000
      LOG_LEVEL: debug
    volumes:
      - ${HOME}/temp/logs:/usr/app/logs
  spdz-proxy1:
    image: spdz/spdz-proxy:v0.4.0
    depends_on:
      - workshop-voting1
    ports:
      - "3011:8080"
    environment:
      SPDZ_HOST: workshop-voting1
      SPDZ_PORT: 14001
      LOG_LEVEL: debug
    volumes:
      - ${HOME}/temp/logs:/usr/app/logs
  workshop-voting-gui:
    image: spdz/workshop-voting-gui:v0.1.4
    depends_on:
      - spdz-proxy0
      - spdz-proxy1
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      LOG_LEVEL: debug
    volumes:
      - ${HOME}/temp/votinggui:/usr/app/config
      - ${HOME}/temp/logs:/usr/app/logs
  nginx-proxy:
    image: nginx:1.12.0
    depends_on:
      - workshop-voting-gui
    ports:
      - "8081:80"
      - "3110:3110"
      - "3111:3111"      
    volumes:
      - ${HOME}/development/spdz-deployment/nginx/voters-dev.conf:/etc/nginx/nginx.conf:ro
      - ${HOME}/development/spdz-deployment/nginx/landingPage:/usr/share/nginx/html      
      - ${HOME}/temp/logs:/var/log/nginx
